import LegalPageLayout from "@/components/legal/LegalPageLayout";
import { buildPageMetadata } from "@/lib/siteMetadata";

const contentSections = [
  {
    title: "Who we are",
    paragraphs: [
      "PP Worldwide Ltd (Company Number 15037470), trading as Performance Peak, is the data controller for personal information collected through this website. We provide digital strategy, AI consultancy and hands-on build services.",
      "If you have questions about how we handle your data, email hello@performancepeak.co.uk.",
    ],
  },
  {
    title: "What we collect and why",
    paragraphs: [
      "Contact form — When you submit our contact form we collect your name, email address and message, plus optional fields for company name and phone number. We use this to respond to your enquiry and, where relevant, prepare a proposal or plan an engagement. The lawful basis is legitimate interests (Article 6(1)(f) UK GDPR): answering a business enquiry that you initiate. We do not use this data for marketing unless you separately opt in.",
      "Analytics cookies — With your consent, we use Google Analytics (GA4) to understand how visitors use the site in aggregate. GA4 sets cookies including _ga (a pseudonymous ID for counting unique visitors, lasting up to two years) and a property-specific session cookie. We have disabled advertising features and Google Signals, and GA4 does not store IP addresses. The lawful basis is consent (Article 6(1)(a)), managed through the cookie banner shown on your first visit.",
      "Local storage — We store a small preference in your browser's local storage to remember whether you prefer the static hero image. This does not contain personal data, expires automatically after 24 hours, and falls under the strictly necessary exemption in PECR.",
    ],
  },
  {
    title: "Data retention",
    paragraphs: [
      "Contact form submissions — We retain enquiry data for up to 12 months from the date of last contact. If your enquiry leads to an engagement, associated project data is retained for the duration of the engagement plus a reasonable wind-down period, after which it is archived or deleted.",
      "Analytics data — Our Google Analytics property retains user-level data for 14 months. Aggregated, non-identifying reports may be kept indefinitely for trend analysis.",
      "You can request deletion of your personal data at any time — see 'Your rights' below.",
    ],
  },
  {
    title: "Who we share data with",
    paragraphs: [
      "We use two third-party data processors to operate this site:",
      "Google LLC (Google Analytics) — processes pseudonymised analytics data in the United States. Google participates in the EU–US Data Privacy Framework and operates under Standard Contractual Clauses (SCCs) for international transfers. Details: policies.google.com/privacy",
      "Resend Inc — delivers the email generated by our contact form. Data is processed in the United States under Standard Contractual Clauses and a Data Processing Agreement. Details: resend.com/legal/privacy-policy",
      "We do not sell, rent or share your personal information with advertisers, marketers or unrelated third parties.",
    ],
  },
  {
    title: "International transfers",
    paragraphs: [
      "Both Google and Resend process data in the United States. We rely on Standard Contractual Clauses (SCCs) approved by the UK Information Commissioner's Office, together with supplementary technical and organisational measures, to ensure your data receives an equivalent level of protection when transferred outside the UK.",
    ],
  },
  {
    title: "How we protect your data",
    paragraphs: [
      "All data transmitted between your browser and our servers is encrypted using TLS. Contact form submissions are delivered via Resend's encrypted API. Project data is stored in secure, access-controlled tools with encrypted backups. Access is limited to the individuals actively supporting your enquiry or engagement.",
    ],
  },
  {
    title: "Your rights",
    paragraphs: [
      "Under UK GDPR you have the right to: access the personal data we hold about you; have inaccurate data rectified; have your data erased ('right to be forgotten'); restrict processing in certain circumstances; receive your data in a structured, machine-readable format (data portability); object to processing based on legitimate interests; and withdraw consent at any time — for analytics cookies, use the 'Manage Cookies' link in our website footer.",
      "To exercise any of these rights, email hello@performancepeak.co.uk. We will respond within one calendar month.",
      "You also have the right to lodge a complaint with the Information Commissioner's Office (ICO) at ico.org.uk if you believe your data protection rights have not been respected.",
    ],
  },
  {
    title: "Automated decision-making",
    paragraphs: [
      "We do not carry out automated decision-making or profiling based on the personal data we collect through this website.",
    ],
  },
  {
    title: "Changes to this policy",
    paragraphs: [
      "We may update this policy from time to time. The date below always reflects the most recent revision. For significant changes we will make reasonable efforts to notify affected individuals.",
      "Last updated: 25 February 2026.",
    ],
  },
];

export const metadata = buildPageMetadata({
  title: "Privacy Policy | Performance Peak",
  description:
    "Understand what data we collect, how we use it, and the controls you have with Performance Peak.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <LegalPageLayout
      heroImage={{ src: "/images/eagle.jpg", alt: "Eagle captured mid flight" }}
      heading={{ leadingText: "Protecting your", highlightText: "privacy" }}
      contactId="privacy-contact"
      contentSections={contentSections}
    />
  );
}
